Eval:
  pred_root: ./result
  gt_root: ./data/TestDataset
  result_path: ./result/metrics
  datasets:
    - CVC-300
    - CVC-ClinicDB
    - CVC-ColonDB
    - ETIS-LaribPolypDB
    - Kvasir
  metrics:
    - meanDic
    - meanIoU
    - wFm
    - Sm
    - maxEm
    - mae
